[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[[chains]]
id = 'stargaze'
rpc_addr = 'http://stargaze:26657'
grpc_addr = 'http://stargaze:9090'
websocket_addr = 'ws://stargaze:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'stars'
key_name = 'relayer'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.025, denom = 'ustars' }
gas_adjustment = 0.1
clock_drift = '300s'
trusting_period = '2days'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'gaia'
rpc_addr = 'http://gaia:26657'
grpc_addr = 'http://gaia:9090'
websocket_addr = 'ws://gaia:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'cosmos'
key_name = 'cosmos'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.025, denom = 'stake' }
gas_adjustment = 0.1
clock_drift = '300s'
trusting_period = '2days'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'osmosis'
rpc_addr = 'http://osmosis:26657'
grpc_addr = 'http://osmosis:9090'
websocket_addr = 'ws://osmosis:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'osmo'
key_name = 'osmosis'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.025, denom = 'uosmo' }
gas_adjustment = 0.1
clock_drift = '300s'
trusting_period = '2days'
trust_threshold = { numerator = '1', denominator = '3' }

[chains.packet_filter]
policy = 'deny'
list = [
  ['ica*', '*'], # deny relaying on all channels whose port starts with `ica`
]
